module.exports.descriptors = [
    'Bosque',
    'Antiguo',
    'Petrificado',
    'Rugiente',
    'Cascada',
    'Cayendo',
    'Silencioso',
    'Secuoya',
    'Rana Toro',
    'Arce',
    'Brumoso',
    'Alce',
    'Oso Grizzly',
    'Océano',
    'Mar',
    'Cielo',
    'Polvoriento',
    'Diamante'
]

module.exports.places = [
    'Llanuras',
    'Pueblo',
    'Cañón',
    'Estanque',
    'Campamento en Grupo',
    'Campamento de Caballos',
    'Pueblo Fantasma',
    'Campamento',
    'Campamento Disperso',
    'Hinterland',
    'Río',
    'Arroyo',
    'Junto al Arroyo',
    'Bahía',
    'Manantial',
    'Costa de la Bahía',
    'Arenas',
    'Campamento de Mulas',
    'Campamento de Caza',
    'Acantilados',
    'Cañada'
]
